// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// my_func
void my_func();
RcppExport SEXP sgpsde_my_func() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    my_func();
    return R_NilValue;
END_RCPP
}
