// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// my_func
void my_func();
RcppExport SEXP sgpsde_my_func() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    my_func();
    return R_NilValue;
END_RCPP
}
// mv
arma::mat mv(arma::vec& x, int nrow, int ncol);
RcppExport SEXP sgpsde_mv(SEXP xSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(mv(x, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// vm
arma::vec vm(arma::mat& x);
RcppExport SEXP sgpsde_vm(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(vm(x));
    return rcpp_result_gen;
END_RCPP
}
