# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mv <- function(x, nrow, ncol) {
    .Call('sgpsde_mv', PACKAGE = 'sgpsde', x, nrow, ncol)
}

vm <- function(x) {
    .Call('sgpsde_vm', PACKAGE = 'sgpsde', x)
}

